---
title: "TCF"
author: "William O'Connor"
date: "2025-05-06"
output: html_document
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(future.globals.maxSize = 80000000000000 * 1024^2, future.seed = TRUE)
set.seed(1234)
suppressPackageStartupMessages(library(Matrix))
suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(SingleCellExperiment))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(yaml))
suppressPackageStartupMessages(library(scDblFinder))
suppressPackageStartupMessages(library(BiocParallel))
suppressPackageStartupMessages(library(scuttle))
suppressPackageStartupMessages(library(scater))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(openxlsx))
suppressPackageStartupMessages(library(destiny))
suppressPackageStartupMessages(library(gam))
suppressPackageStartupMessages(library(ggthemes))
suppressPackageStartupMessages(library(pheatmap))
suppressPackageStartupMessages(library(viridis))
suppressPackageStartupMessages(library(Hmisc))
suppressPackageStartupMessages(library(org.Mm.eg.db))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(cowplot))
library(fgsea)
library(dplyr)
library(ggh4x)
library(limma)
#library(RColorBrewer)

```

```{r general_functions}
# much faster `merge` on matrices (assumes `by = "row.names"`)
merge.matrices <- function (x,y) {
  xy.names <- union(row.names(x),row.names(y))
  missing.x <- setdiff(row.names(y),row.names(x))
  x <- rbind(x,`row.names<-`(matrix(0,nrow = length(missing.x),ncol = ncol(x)),missing.x))
  missing.y <- setdiff(row.names(x),row.names(y))
  y <- rbind(y,`row.names<-`(matrix(0,nrow = length(missing.y),ncol = ncol(y)),missing.y))
  return(cbind2(x[xy.names,],y[xy.names,]))
}
findgenes <- function(obj,startstr){
  row.names(obj@assays$RNA@counts)[grepl(paste0("^",startstr),row.names(obj@assays$RNA@counts))]
}
```

# Whole Liver

## Load and consolidate data

```{r load_data}
# import sample data 
samples <- normalizePath(dir("Chromium-SC3Pv3",full.names=T))
samples <- samples[c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)]
print(samples)

names(samples) <- basename(samples)
nonexistant <- !dir.exists(samples)
samples <- samples[!nonexistant]
if (length(samples) == 0) stop("No valid samples. Nothing to do.")

# load in barcodes
barcode.files <- file.path(samples,"counts_cellbender.barcodes.txt")
names(barcode.files) <- names(samples)
nonexistant <- !file.exists(barcode.files)
samples <- samples[!nonexistant]
if (length(samples) == 0) stop("No valid samples. Nothing to do.")
barcodes <- barcode.files %>%
  lapply(readr::read_lines) %>%
  purrr::imap(~ sprintf("%s.%s",.y,.x))

# load in features
feature.files <- file.path(samples,"counts_cellbender.features.txt")
names(feature.files) <- names(samples)
nonexistant <- !file.exists(feature.files)
samples <- samples[!nonexistant]
if (length(samples) == 0) stop("No valid samples. Nothing to do.")
features <- feature.files %>%
  lapply(readr::read_lines)

# load in counts
count.files <- file.path(samples,"counts_cellbender.mtx.gz")
names(count.files) <- names(samples)
nonexistant <- !file.exists(count.files)
samples <- samples[!nonexistant]
if (length(samples) == 0) stop("No valid samples. Nothing to do.")
counts <- count.files %>%
  lapply(Matrix::readMM) %>%
  purrr::imap(~ `colnames<-`(.x,barcodes[[.y]])) %>%
  purrr::imap(~ `row.names<-`(.x,features[[.y]])) %>%
  purrr::reduce(merge.matrices)

# load in metadata
metadata.files <- file.path(samples,"sample.yaml")
names(metadata.files) <- names(samples)
nonexistant <- !file.exists(metadata.files)
samples <- samples[!nonexistant]
if (length(samples) == 0) stop("No valid samples. Nothing to do.")
barcodes <- barcodes %>%
  purrr::imap(~ data.frame(hashtag = .y,cell = .x)) %>%
  plyr::ldply(.id = "hashtag")
metadata <- metadata.files %>%
  lapply(yaml::read_yaml) %>%
  lapply(data.frame,stringsAsFactors = FALSE) %>%
  plyr::ldply(.id = "name") %>%
  dplyr::rename("hashtag" = "name") %>%
  dplyr::right_join(barcodes,by = "hashtag") %>%
  dplyr::mutate(sample = stringr::str_remove(hashtag,"[A-Z]$")) %>%
  dplyr::select(cell,sample,hashtag,tidyselect::everything()) %>%
  tibble::column_to_rownames("cell")
n.grid <- ceiling(sqrt(length(unique(metadata$sample))))

```

## Create Seurat Objects and QC

```{r seurat_obj_plus_QC}
# build object
seurat_obj <- counts %>%
  SeuratObject::CreateSeuratObject(project = "Core-Biddinger",meta.data = metadata, min.cells=3, min.features=200) %>%
  Seurat::PercentageFeatureSet(pattern = "^[Mm][Tt]-",col.name = "mt.percent")

# no doublets
sce <- as.SingleCellExperiment(seurat_obj)
sce <- scDblFinder(sce, 
                   samples=sce$orig.ident,
                   BPPARAM=SnowParam(8, RNGseed=1234))

single_cell_results <- sce$scDblFinder.class
seurat_obj@meta.data$scdbl <- single_cell_results
filtered_seurat <- subset(x = seurat_obj, 
                         subset= (nFeature_RNA > 500) & 
                           (mt.percent <= 2) & 
                           (scdbl=='singlet'))
rm(sce)
```

## SCTransform, Integration, and Clustering

```{r integration_fns}
normalize <- function(seurat_obj, rgrslist, nfeat){
  split_seurat <- seurat_obj %>%
    Seurat::SplitObject(split.by = "sample") %>%
    lapply(Seurat::SCTransform,vars.to.regress = rgrslist,verbose = FALSE)
  split_seurat <- SplitObject(seurat_obj, split.by = "sample")

  for (i in 1:length(split_seurat)) {
     split_seurat[[i]] <- SCTransform(split_seurat[[i]], vars.to.regress = rgrslist)#, vst.flavor = "v2")
  }

  integ_features <- SelectIntegrationFeatures(object.list = split_seurat, nfeatures = nfeat,verbose = FALSE)

  split_seurat <- PrepSCTIntegration(object.list = split_seurat, anchor.features = integ_features)

  integ_anchors <- FindIntegrationAnchors(object.list = split_seurat, normalization.method = "SCT", anchor.features = integ_features) # 15-20 mins
  return(integ_anchors)
}
integrate <- function(anchors){
  seurat_integrated <- IntegrateData(anchorset = anchors, normalization.method = "SCT")
  return(seurat_integrated)
}
postintegrate <- function(seurat_obj, pcadim, rsltn){
  seurat_obj <- RunPCA(object = seurat_obj)
  seurat_obj <- RunUMAP(seurat_obj, dims = 1:pcadim,reduction = "pca")
  seurat_obj <- FindNeighbors(object = seurat_obj, dims = 1:pcadim,reduction='pca')
  seurat_obj <- FindClusters(object = seurat_obj,resolution = c(rsltn))
  return(seurat_obj)
}
```

```{r integrate}
anchs <- normalize(filtered_seurat,c("mt.percent","nCount_RNA","nFeature_RNA"),3000)#
rm(barcodes,counts,features,filtered_seurat,seurat_obj,single_cell_results,metadata)
#saveRDS(anchs,"anchs_test.rds")
#anchs <- readRDS("anchs_test.rds")
seurat_integrated <- integrate(anchs)
seurat_integrated <- postintegrate(seurat_integrated,12,0.12)
DefaultAssay(seurat_integrated) <- "RNA"
seurat_integrated <- NormalizeData(seurat_integrated)
seurat_integrated <- ScaleData(seurat_integrated)
saveRDS(seurat_integrated,"TCF_Knockout_seurat_integrated_mtcountfeat_012.rds")
```

## Cell Type

```{r celltypeheatmap}
genes <- c("Alb","Ttr","Hnf4a","Krt19","Sox9","Epcam","Cd3d","Cd3g","Ms4a1","Cd79b","Cd19","Ncr1","Gzma","Nkg7","Csf3r","S100a8","Itgax","Ccr2","Ly6c2","Adgre1","Csf1r","Stab1","Stab2","Lyve1","Fcgr2b","Flt4","Vwf","Myh11","Cnn1","Mfap4","Col15a1","Thy1","Lrat","Reln","Des","Dcn")#F4/80->Adgre1;Nkp46->Ncr1;Nk7g->Nkg7
types <- c("HEP","HEP","HEP","CHOL","CHOL","CHOL","T-Cell","T-Cell","B-Cell","B-Cell","B-Cell","NK Cell","NK Cell","NK Cell","Neutrophil","Neutrophil","DC","Monocyte","Monocyte","Macrophage","Macrophage","LSEC","LSEC","LSEC","LSEC","LSEC","VEC","VSMC","VSMC","PF","PF","PF","HSC","HSC","HSC","HSC")
goi <- data.frame(genes,types)


DefaultAssay(seurat_integrated) <- "RNA"
seurat_integrated <- NormalizeData(seurat_integrated)
seurat_integrated <- ScaleData(seurat_integrated)


avg_expr <- AverageExpression(object = seurat_integrated, group.by="seurat_clusters",slot='data',features=goi$genes)$RNA
newnames <- lapply(
  rownames(avg_expr),
    function(x) bquote(bolditalic(.(x))))#capitalize(

newcolnames <- lapply(
  colnames(avg_expr),
  function(x) bquote(bolditalic(.(x))))#capitalize(

anno_table <- as.data.frame(goi)
rownames(anno_table) <- goi$gene



anno_table <- anno_table[,"types", drop = F] #%>%
colnames(anno_table) <- "Cell Type"

annotation_colors <- list(cell_type = c(
  `B-Cell` = "#B6992D",
  `T-Cell` = "#92D",
  `NK Cell` = "gray",
  Neutrophil = "black",
  Monocyte = "blue",
  Macrophage = "red",
  VEC = "pink",
  PF = "green",
  VSMC = "darkgreen",
  CHOL = "#8CD17D",
  HEP = "#4E79A7",
  DC = "#F28E2B",
  LSEC = "#A0CBE8",
  HSC = "#FFBE7D"
))


pheatmap(avg_expr,
         annotation_row = anno_table,
         annotation_colors = annotation_colors,
         color = colorRampPalette(c('#408697','#F6F6F6','#8F0009'))(255),
         scale = 'row',
         fontsize = 12,
         fontsize_col = 14,
         angle_col = "45",
         cluster_rows = F,
         cluster_cols = F,
         labels_row = as.expression(newnames),
         labels_col = as.expression(newcolnames),
         annotation_names_row = F,
         treeheight_row = 55,
         treeheight_col = 55,
         cellwidth = 30,
#         filename = "celltype_heatmap_cluster_murine.png"
         )

```

```{r cell_type_assignment}
proj_name <- "TCF_Knockout"
cluster_assn <- read_csv(paste0(proj_name, '_cluster_assignment_012.csv'))
cluster_assn <- cluster_assn%>%
  mutate(cluster_assignment = paste(cluster_assn$Cluster, cluster_assn$Assignment, sep = "_"))

Idents(seurat_integrated) <- "seurat_clusters"

seurat_integrated[["cluster_id_named"]] <- plyr::mapvalues(Idents(seurat_integrated),
                                                    from=cluster_assn$Cluster,
                                                    to=cluster_assn$cluster_assignment)

new.cluster.ids <- cluster_assn$Assignment

names(new.cluster.ids) <- levels(seurat_integrated)
seurat_integrated <- RenameIdents(seurat_integrated, new.cluster.ids)

seurat_integrated[["cluster_named"]] <- Idents(seurat_integrated)


cluster_named_plot <- DimPlot(seurat_integrated, reduction = "umap", label = TRUE, pt.size = 0.5) + NoLegend() 
cluster_named_plot

ggsave(paste0("umap_celltype_012.png"), cluster_named_plot, units = 'in', width = 6, height = 6, dpi = 250)

saveRDS(seurat_integrated, "TCF_Knockout_seurat_integrated_mtcountfeat_012.rds")
```

```{r S2D}
avg_expr <- AverageExpression(object = seurat_integrated, group.by="cluster_named",slot='data',features=goi$genes)$RNA
avg_expr <- avg_expr[c(1:3,22:27,4:6,33:36,28:32,15:16,7:14,17:21),c(1,2,3,7,5,4,6)]

pheatmap(avg_expr,
         annotation_row = anno_table,
         annotation_colors = annotation_colors,
         color = colorRampPalette(c('#408697','#F6F6F6','#8F0009'))(255),
         scale = 'row',
         fontsize = 12,
         fontsize_col = 14,
         angle_col = "45",
         cluster_rows = F,
         cluster_cols = F,
         labels_row = as.expression(newnames),
         labels_col = as.expression(newcolnames),
         annotation_names_row = F,
         treeheight_row = 55,
         treeheight_col = 55,
         cellwidth = 30,
         filename = "celltype_heatmap_celltype_murine.png"
         )

```

```{r S2E}
d <- as.data.frame(table(seurat_integrated@meta.data$perturbation, seurat_integrated@meta.data$cluster_named, seurat_integrated@meta.data$sample))
colnames(d) <- c("Condition","Cluster","Sample","Cell Count")
d<-d[-which(d$`Cell Count`==0),]
x<-aggregate(d$`Cell Count`,by=list(c(d$Sample)),sum)
colnames(x)<-c("Sample","Sample Sum")
d<-merge(d,x,by="Sample")
d$pct<-100*d$`Cell Count`/d$`Sample Sum`
d$Cluster <- factor(d$Cluster, levels = c("HEP1", "HEP2","ENDO","IMM1","MES","IMM2","CHOL"), ordered = TRUE)
d[,c(1:3,6)]%>%write.csv("S2Edata.csv",row.names=F)
```

## Umap

```{r F2B}
Idents(seurat_integrated) <- "cluster_named"
cluster_named_plot <- DimPlot(seurat_integrated, reduction = "umap", label = F, pt.size = 0.5)# + NoLegend() + theme(axis.line =element_blank(),axis.text =element_blank(),axis.title =element_blank(),axis.ticks = element_blank())
cluster_named_plot

ggsave(paste0("umap_clusters_012.png"), cluster_named_plot, units = 'in', width = 6, height = 6, dpi = 250)
```

```{r S3A-C}
FeaturePlot(seurat_integrated,
            reduction = "umap",
            features = "nFeature_RNA",
            pt.size = 0.4,
            order = TRUE,
            min.cutoff = 'q10')# + NoLegend() + theme(axis.line =element_blank(),axis.text =element_blank(),axis.title =element_blank(),axis.ticks = element_blank())+labs(title=element_blank())
ggsave("umap_nfeature.png",last_plot(), units = 'in', width = 6, height = 6, dpi = 250)

Idents(seurat_integrated) <- "perturbation"
DimPlot(seurat_integrated,label = F, split.by = "perturbation")# + NoLegend()+ theme(axis.line =element_blank(),axis.text =element_blank(),axis.title =element_blank(),axis.ticks = element_blank())+labs(title=element_blank())+theme(strip.text.x = element_blank() )
ggsave("umap_perturbation.png",last_plot(), units = 'in', width = 8.48, height = 4.24, dpi = 250)


seurat_integrated <- CellCycleScoring(
     seurat_integrated,
     s.features = str_to_title(cc.genes$s.genes),
     g2m.features = str_to_title(cc.genes$g2m.genes),
     assay = 'RNA',
     set.ident = TRUE)

Idents(seurat_integrated) <- "Phase"
DimPlot(seurat_integrated, 
        label = F, split.by = "Phase",ncol = 3)#  + NoLegend()+ theme(axis.line =element_blank(),axis.text =element_blank(),axis.title =element_blank(),axis.ticks = element_blank())+labs(title=element_blank())+theme(strip.text.x = element_blank() )
ggsave("umap_cycle.png",last_plot(), units = 'in', width = 10.38, height = 3.46, dpi = 250)


Idents(seurat_integrated) <- "sample"
levels(seurat_integrated)
colorlist <- c("#B6992D","#8CD17D","#4E79A7","#F28E2B","#A0CBE8","#F1CE63","#86BCB6","#FFBE7D","#3F8455","#3E4087")
samsplit <- SplitObject(seurat_integrated, split.by = "sample")
for (i in 1:nlevels(Idents(seurat_integrated))) {
  DimPlot(samsplit[[i]],label = FALSE, split.by = "sample",cols=c(colorlist[i]),ncol = 3)#  + NoLegend()+ theme(axis.line =element_blank(),axis.text =element_blank(),axis.title =element_blank(),axis.ticks = element_blank())+labs(title=element_blank())+theme(strip.text.x = element_blank() )
  ggsave(paste("umap_sample",toString(i),".png"),last_plot(), units = 'in', width = 6, height = 6, dpi = 250)
}
```

# Hepatocytes Only

## Subset

```{r subsetheponly}
Idents(seurat_integrated) <- "seurat_clusters"
# DimPlot(seurat_integrated, reduction = "umap", label = F, pt.size = 0.5)
sub_obj <- subset(x = seurat_integrated, idents =  c("0","1"))
DefaultAssay(sub_obj) <- "RNA"
```

## UMAPs

```{r umap}
DimPlot(sub_obj,reduction = "umap",label = TRUE,label.size = 6)
ggsave("umap_2hepclustersonly.png",last_plot())
```

```{r F2C}
genes <- read_csv("gene_sets/pp_vs_pc.csv")
sub_obj$PCavg <- colMeans(x=sub_obj@assays$RNA@scale.data[genes$Pericentral[1:9],],na.rm= TRUE)
#
sub_obj$PPavg <- colMeans(x = sub_obj@assays$RNA@scale.data[genes$Periportal, ], na.rm = TRUE)

p <- FeaturePlot(sub_obj,
            reduction = "umap",
            features = c('PCavg','PPavg'),
            slot = "data",
            pt.size = 0.15,
            order = T,
            #min.cutoff = 'q10',
            ncol = 1,
            keep.scale = "feature",
            blend=T,
            blend.threshold = 0.25,
            split.by = "perturbation",
            #combine=F,
            cols=c('#F6F6F6','#408697','#8F0009'),
            label = FALSE)
p3 <- p[[7]]+theme(axis.title = element_blank(),axis.ticks=element_blank(),axis.text = element_blank(),axis.line = element_blank())+labs(title=element_blank(),y=element_blank(),x=element_blank())+ theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))+coord_fixed()

p6 <- p[[3]]+theme(axis.title = element_blank(),axis.ticks=element_blank(),axis.text = element_blank(),axis.line = element_blank())+labs(title=element_blank(),y=element_blank(),x=element_blank())+ theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))+coord_fixed()
x <- p[[4]]
x <- p[[4]]$data
x <- x[x$rows%in%c(1,5,10)&x$cols%in%c(1,5,10),]
x[x$rows==1,]$rows <- "Low"
x[x$rows==5,]$rows <- "Med"
x[x$rows==10,]$rows <- "High"
x[x$cols==1,]$cols <- "Low"
x[x$cols==5,]$cols <- "Med"
x[x$cols==10,]$cols <- "High"
row.names(x) <- NULL
p7 <- ggplot(x,aes(x=fct_inorder(rows),y=fct_inorder(cols),fill=vals))+theme_classic()+geom_raster()+scale_fill_manual(values = c(p[[4]]$plot_env$color.matrix[c(1,5,10),c(1,5,10)]))+NoLegend()+labs(title = element_blank(),x=element_blank(),y=element_blank())+theme(axis.title = element_blank(),title = element_blank(),axis.text = element_blank(),axis.line =element_blank(),axis.ticks = element_blank())+coord_fixed()

p3+ panel_border(remove = TRUE)
ggsave("umap_pcvpp_012_avgzscoretest_nolabels_WT_final.png",last_plot(),width = 6, height=6,dpi=250, bg = "white")
p6+ panel_border(remove = TRUE)
ggsave("umap_pcvpp_012_avgzscoretest_nolabels_KO_final.png",last_plot(),width = 6, height=6,dpi=250, bg = "white")
p7+ panel_border(remove = TRUE)
ggsave("umap_pcvpp_012_avgzscoretest_nolabels_legend_final.png",last_plot(),width = 6, height=6,dpi=250, bg = "white")
```

## MSigDB

```{r F3A_S4A}
sub_obj <- subset(x = seurat_integrated, idents =  c("0"))#periportal cluster
avg_expr <- as.data.frame(AverageExpression(sub_obj, group.by="sample")$SCT)

avg_expr <- add_column(avg_expr, NAME=rownames(avg_expr), .before=1)
avg_expr <- avg_expr %>%rowwise()%>%mutate(S2RsdW=max(abs(mean(c_across("Mm_liver_WT_01-2":"Mm_liver_WT_05-1")))*0.2,sd(c_across("Mm_liver_WT_01-2":"Mm_liver_WT_05-1"))))#
avg_expr <- avg_expr %>%rowwise()%>%mutate(S2Rsdko=max(abs(mean(c_across("Mm_liver_TCF4-KO_06-2":"Mm_liver_TCF4-KO_10-1")))*0.2,sd(c_across("Mm_liver_TCF4-KO_06-2":"Mm_liver_TCF4-KO_10-1"))))
avg_expr <- avg_expr %>%rowwise()%>%mutate(S2R=(mean(c_across("Mm_liver_TCF4-KO_06-2":"Mm_liver_TCF4-KO_10-1"))-mean(c_across("Mm_liver_WT_01-2":"Mm_liver_WT_05-1")))/(S2Rsdko+S2RsdW))

write.table(avg_expr, "cluster_0_KO_vs_WT_res012_results.txt", sep="\t", quote=FALSE, row.names=FALSE)

sub_obj <- subset(x = seurat_integrated, idents =  c("1"))#pericentral cluster
avg_expr <- as.data.frame(AverageExpression(sub_obj, group.by="sample")$SCT)

avg_expr <- add_column(avg_expr, NAME=rownames(avg_expr), .before=1)
avg_expr <- avg_expr %>%rowwise()%>%mutate(S2RsdW=max(abs(mean(c_across("Mm_liver_WT_01-2":"Mm_liver_WT_05-1")))*0.2,sd(c_across("Mm_liver_WT_01-2":"Mm_liver_WT_05-1"))))#
avg_expr <- avg_expr %>%rowwise()%>%mutate(S2Rsdko=max(abs(mean(c_across("Mm_liver_TCF4-KO_06-2":"Mm_liver_TCF4-KO_10-1")))*0.2,sd(c_across("Mm_liver_TCF4-KO_06-2":"Mm_liver_TCF4-KO_10-1"))))
avg_expr <- avg_expr %>%rowwise()%>%mutate(S2R=(mean(c_across("Mm_liver_TCF4-KO_06-2":"Mm_liver_TCF4-KO_10-1"))-mean(c_across("Mm_liver_WT_01-2":"Mm_liver_WT_05-1")))/(S2Rsdko+S2RsdW))

write.table(avg_expr, "cluster_1_KO_vs_WT_res012_results.txt", sep="\t", quote=FALSE, row.names=FALSE)
```

## WTvsKOvsPCvsPP

```{r WTvsKOvsPCvsPP}
Idents(seurat_integrated) <- "seurat_clusters"
sub_obj <- subset(x = seurat_integrated, idents =  c("0","1"))
# get average expression for pc vs pp for both KO and WT
avgexp <- as.data.frame(AverageExpression(sub_obj,assays="RNA",group.by=c("seurat_clusters","perturbation")))
avgexp$gene <- row.names(avgexp)
# prep t tests
meta <- sub_obj@meta.data[c('seurat_clusters','perturbation')]
exp_df <- sub_obj@assays$RNA@data[,] %>% as.matrix() %>% t() %>% as.data.frame()
df <- merge(meta, exp_df, by = 0)
genes <- rownames(sub_obj)

# run t tests
## WT PC vs PP
sub_df <- df[df$perturbation=="WT",]
names(sub_df)[length(names(sub_df))]
names1 <- rbindlist(list(lapply(names(sub_df)[-c(1,2,3)],function(x) x)))%>%t()%>%as.data.frame()#
results1 <- lapply(names(sub_df)[-c(1,2,3)],function(x) tryCatch(t.test(as.formula(paste(paste0("`",x,"`"),"seurat_clusters",sep="~")),data=sub_df)[[3]], error=function(e) NaN)) #NaN[-c(1,2,length(names(sub_df)))]
results1df <- rbindlist(list(results1))%>%t()%>%as.data.frame()
results1df$gene <- names1$V1
colnames(results1df) <- c('WT p-value','gene')
## KO PC vs PP
sub_df <- df[df$perturbation=="KO",]
names2 <- rbindlist(list(lapply(names(sub_df)[-c(1,2,3)],function(x) x)))%>%t()%>%as.data.frame()#
results2 <- lapply(names(sub_df)[-c(1,2,3)],function(x) tryCatch(t.test(as.formula(paste(paste0("`",x,"`"),"seurat_clusters",sep="~")),data=sub_df)[[3]], error=function(e) NaN))
results2df <- rbindlist(list(results2))%>%t()%>%as.data.frame()
results2df$gene <- names2$V1
colnames(results2df) <- c('KO p-value','gene')
## PC WT vs KO
sub_df <- df[df$seurat_clusters=="1",]
names3 <- rbindlist(list(lapply(names(sub_df)[-c(1,2,3)],function(x) x)))%>%t()%>%as.data.frame()#
results3 <- lapply(names(sub_df)[-c(1,2,3)],function(x) tryCatch(t.test(as.formula(paste(paste0("`",x,"`"),"perturbation",sep="~")),data=sub_df)[[3]], error=function(e) NaN))
length(results3)
results3df <- rbindlist(list(results3))%>%t()%>%as.data.frame()
results3df$gene <- names3$V1
colnames(results3df) <- c('PC p-value','gene')
## PP WT vs KO
sub_df <- df[df$seurat_clusters=="0",]
names4 <- rbindlist(list(lapply(names(sub_df)[-c(1,2,3)],function(x) x)))%>%t()%>%as.data.frame()#
results4 <- lapply(names(sub_df)[-c(1,2,3)],function(x) tryCatch(t.test(as.formula(paste(paste0("`",x,"`"),"perturbation",sep="~")),data=sub_df)[[3]], error=function(e) NaN))
results4df <- rbindlist(list(results4))%>%t()%>%as.data.frame()
results4df$gene <- names4$V1
colnames(results4df) <- c('PP p-value','gene')
# results[,c("PC WT","PC KO","PP WT","PP KO")] <- c(avgexp$RNA.1_WT,avgexp$RNA.1_KO,avgexp$RNA.0_WT,avgexp$RNA.0_KO)
results <- merge(results1df,results2df)
results <- merge(results,results3df)
results <- merge(results,results4df)
results <- merge(results,avgexp)
colnames(results) <- c('gene','WT (PC vs PP) p-value','KO (PC vs PP) p-value','PC (WT vs KO) p-value','PP (WT vs KO) p-value','PP KO','PP WT','PC KO', 'PC WT')#,'WT (PC vs PP) log2fc','KO (PC vs PP) log2fc','PC (WT vs KO) log2fc','PP (WT vs KO) log2fc'


results$`WT (PC vs PP) FDR` <- p.adjust(results$`WT (PC vs PP) p-value`,method="BH")
results$`KO (PC vs PP) FDR` <- p.adjust(results$`KO (PC vs PP) p-value`,method="BH")
results$`PC (WT vs KO) FDR` <- p.adjust(results$`PC (WT vs KO) p-value`,method="BH")
results$`PP (WT vs KO) FDR` <- p.adjust(results$`PP (WT vs KO) p-value`,method="BH")

colnames(results) <- c('gene','WT (PC vs PP) p-value','KO (PC vs PP) p-value','PC (WT vs KO) p-value','PP (WT vs KO) p-value','PP KO','PP WT','PC KO', 'PC WT',"WT (PC vs PP) FDR","KO (PC vs PP) FDR","PC (WT vs KO) FDR",'PP (WT vs KO) FDR')#,'WT (PC vs PP) log2fc','KO (PC vs PP) log2fc','PC (WT vs KO) log2fc','PP (WT vs KO) log2fc'
results[results$`PP KO`==0,]$`PP KO` <- 10^-5
results[results$`PC KO`==0,]$`PC KO` <- 10^-5
results[results$`PP WT`==0,]$`PP WT` <- 10^-5
results[results$`PC WT`==0,]$`PC WT` <- 10^-5

results$`WT (PC vs PP) log2fc` <- log2(results$`PC WT`/results$`PP WT`)
results$`KO (PC vs PP) log2fc` <- log2(results$`PC KO`/results$`PP KO`)
results$`PC (WT vs KO) log2fc` <- log2(results$`PC WT`/results$`PC KO`)
results$`PP (WT vs KO) log2fc` <- log2(results$`PP WT`/results$`PP KO`)



results%>%write_csv("avgexpttest.csv")
results <- read.csv("avgexpttest.csv")
colnames(results) <- c('gene','WT (PC vs PP) p-value','KO (PC vs PP) p-value','PC (WT vs KO) p-value','PP (WT vs KO) p-value','PP KO','PP WT','PC KO', 'PC WT',"WT (PC vs PP) FDR","KO (PC vs PP) FDR","PC (WT vs KO) FDR",'PP (WT vs KO) FDR','WT (PC vs PP) log2fc','KO (PC vs PP) log2fc','PC (WT vs KO) log2fc','PP (WT vs KO) log2fc')

splitobj <- SplitObject(sub_obj, split.by = "perturbation")
just_WT <- splitobj$WT
just_KO <- splitobj$KO
splitobj <- SplitObject(sub_obj, split.by = "seurat_clusters")
just_PP <- splitobj$`0`
just_PC <- splitobj$`1`

PCcells <- rowSums(GetAssayData(object = just_PC, slot = "data")[,]>0)
PCcells <- data.frame(PCcells)
PCcells$'gene' <-  rownames(PCcells)
PPcells <- rowSums(GetAssayData(object = just_PP, slot = "data")[,]>0)
PPcells <- data.frame(PPcells)
PPcells$'gene' <-  rownames(PPcells)
KOcells <- rowSums(GetAssayData(object = just_KO, slot = "data")[,]>0)
KOcells <- data.frame(KOcells)
KOcells$'gene' <-  rownames(KOcells)
WTcells <- rowSums(GetAssayData(object = just_WT, slot = "data")[,]>0)
WTcells <- data.frame(WTcells)
WTcells$'gene' <-  rownames(WTcells)
cells <- merge(WTcells,KOcells,by='gene')
cells <- merge(cells,PCcells,by='gene')
cells <- merge(cells,PPcells,by='gene')
cresults <- merge(results,cells,by='gene')
cresults%>%write_csv("avgexpttest_withcells.csv")
```

```{r F2D}
cresults <- read.csv("avgexpttest_withcells.csv")
colnames(cresults) <- c('gene','WT (PC vs PP) p-value','KO (PC vs PP) p-value','PC (WT vs KO) p-value','PP (WT vs KO) p-value','PP KO','PP WT','PC KO', 'PC WT',"WT (PC vs PP) FDR","KO (PC vs PP) FDR","PC (WT vs KO) FDR",'PP (WT vs KO) FDR','WT (PC vs PP) log2fc','KO (PC vs PP) log2fc','PC (WT vs KO) log2fc','PP (WT vs KO) log2fc',"WTcells","KOcells","PCcells","PPcells")
cresults$WTcells <- cresults$WTcells/9336
cresults$KOcells <- cresults$KOcells/9781

fdr <- pivot_longer(cresults[,c(1,10,11)],cols=c(2,3),names_to = ('genotype'))
colnames(fdr)[3] <- "FDR"
fdr$genotype <- substr(fdr$genotype,1,2)
cells <- pivot_longer(cresults[,c(1,18,19)],cols=c(2,3),names_to = ('genotype'))
colnames(cells)[3] <- "Cells"
cells$genotype <- substr(cells$genotype, 1, 2)
fc <- pivot_longer(cresults[,c(1,14,15)],cols=c(2,3),names_to = ('genotype'))
colnames(fc)[3] <- "Log2FC"
fc$genotype <- substr(fc$genotype,1,2)
results <- merge(fdr,cells)
results <- merge(results,fc)
results <- results[results$FDR<0.05&results$Cells>0.1,]
rs <- results[,c(1,2,5)]
resultsw <- pivot_wider(rs,names_from = genotype,values_from = Log2FC)

ggplot(resultsw,aes(x=WT,y=KO))+ coord_axes_inside(labels_inside = TRUE) +geom_point(color="#8d8c8a") +geom_smooth(method='lm',color="#8f0009",linewidth=1.5,se=F,fullrange=F) +geom_segment(x=-6,y=-6,xend=6,yend=6,linetype=2,linewidth=1.5)+scale_y_continuous(limits = c(-6,6),minor_breaks = NULL,breaks=c(-6,-3,0,3,6))+scale_x_continuous(limits = c(-6,6),minor_breaks = NULL,breaks=c(-6,-3,0,3,6))#+theme_classic()+labs(title=element_blank(),y=element_blank(),x=element_blank())+theme(axis.text = element_blank(),axis.line = element_line(colour = 'black', size = 1.5),axis.ticks = element_line(colour = 'black', size = 1.5),axis.ticks.length = unit(0.3,"cm"))#slope = 1,intercept = 0
ggsave("fcWTvKO_10pct_8f009fullrange.png",width=6, height=6)#,dpi=1200)
```

# Reintegrated Hepatocyte Object

## Reintegrating

```{r reintegrate}
hepatocyte_obj <- subset(x = seurat_integrated, subset = (cluster_named%in%c("HEP1","HEP2")))
reint_anchs <- normalize(hepatocyte_obj,c("mt.percent","nFeature_RNA","nCount_RNA"),3000)
rm(hepatocyte_obj,seurat_integrated,seurat_obj)
saveRDS(reint_anchs,"reint_anchs_012.rds")
reint_anchs <- readRDS("reint_anchs_012.rds")
hepatocyte_obj_reint <- integrate(reint_anchs)
hepatocyte_obj_reint <- postintegrate(hepatocyte_obj_reint,30,0.9)
saveRDS(hepatocyte_obj_reint,"hepatocyte_obj_reint_mtcountfeat_prefiltering.rds")
hepatocyte_obj_reint <- readRDS("hepatocyte_obj_reint_mtcountfeat_prefiltering.rds")
tapply(hepatocyte_obj_reint$seurat_clusters,hepatocyte_obj_reint$seurat_clusters,length)#print cells per cluster

Idents(hepatocyte_obj_reint) <- "seurat_clusters"
DimPlot(hepatocyte_obj_reint,reduction = "umap",label = TRUE,label.size = 6)
ggsave("umap_012_hepreint_prefiltering.png",last_plot())
```

```{r dpt}
hepatocyte_obj_reint <- subset(x = hepatocyte_obj_reint, idents =  c("0","1","2","3","4","5","6","7","8","9","10","11","12","13","16"))#,"14","15","17","18"
DimPlot(hepatocyte_obj_reint,reduction = "umap",label = TRUE,label.size = 6)


ggsave("umap_reint.png",last_plot())
dm <- DiffusionMap(Embeddings(hepatocyte_obj_reint, "pca")[,1:20])
dpt <- DPT(dm)

hepatocyte_obj_reint$dpt <- rank(dpt$dpt)
dpt_vals <- hepatocyte_obj_reint$dpt

hepatocyte_obj_reint$dpt <- -((dpt_vals-min(dpt_vals))/(max(dpt_vals)-min(dpt_vals)))+1
hepatocyte_obj_reint$dpt <- hepatocyte_obj_reint$dpt*8+1


meta <- hepatocyte_obj_reint@meta.data

tmp <- data.frame(DC1 = eigenvectors(dm)[, 1],
                  DC2 = eigenvectors(dm)[, 2],
                  DC3 = eigenvectors(dm)[, 3],
                  DC4 = eigenvectors(dm)[, 4],
                  cluster = hepatocyte_obj_reint$seurat_clusters,
                  dpd = dpt_vals)

dc_scatter_by_dpd <- ggplot(tmp, aes(x = DC1, y = DC2, colour = dpd)) + geom_point() + 
                            xlab("DC 1") + ylab("DC 2") + theme_few()
dc_scatter_by_cluster <- ggplot(tmp, aes(x = DC1, y = DC2, colour=cluster)) + geom_point() +
                            xlab("DC 1") + ylab("DC 2") + theme_few()
dc_scatter_by_cluster
ggsave("scatter_cluster_012_reint.png",last_plot())
dc_scatter_by_dpd
ggsave("scatter_dpd_012_reint.png",last_plot())

DefaultAssay(hepatocyte_obj_reint) <- "RNA"
hepatocyte_obj_reint <- NormalizeData(hepatocyte_obj_reint)
hepatocyte_obj_reint <- ScaleData(hepatocyte_obj_reint)
min(hepatocyte_obj_reint@assays$RNA@data)
dpt_vals <- hepatocyte_obj_reint$dpt
hepatocyte_obj_reint$dpt <- ((dpt_vals-min(dpt_vals))/(max(dpt_vals)-min(dpt_vals)))#-+1
hepatocyte_obj_reint$dpt <- hepatocyte_obj_reint$dpt*8
hepatocyte_obj_reint$binneddptgeno <- as.factor(paste0(hepatocyte_obj_reint$perturbation,"_",ceiling(hepatocyte_obj_reint$dpt)))
table(hepatocyte_obj_reint$binneddptgeno)
hepatocyte_obj_reint@meta.data$binneddptgeno[which(hepatocyte_obj_reint@meta.data$binneddptgeno == "KO_0")] <- "KO_1" # moves the one cell in bin KO_1 to KO_2
table(hepatocyte_obj_reint$binneddptgeno)
saveRDS(hepatocyte_obj_reint,"hepatocyte_obj_012_reint_mtcountfeat.rds")
```

## Zonated Genes

```{r getzonatedgenes gam}
just_WT <- SplitObject(hepatocyte_obj_reint, split.by = "perturbation")
just_WT <- just_WT$WT
WT_genes <- rownames(just_WT)
WT_meta <- just_WT@meta.data['dpt']
exp_df <- just_WT@assays$RNA@data[WT_genes,] %>% as.matrix() %>% t() %>% as.data.frame()
WT_df <- merge(WT_meta, exp_df, by = 0)

just_KO <- SplitObject(hepatocyte_obj_reint, split.by = "perturbation")
just_KO <- just_KO$KO
KO_genes <- rownames(just_KO)
KO_meta <- just_KO@meta.data['dpt']
exp_df <- just_KO@assays$RNA@data[KO_genes,] %>% as.matrix() %>% t() %>% as.data.frame()
KO_df <- merge(KO_meta, exp_df, by = 0)


genes <- intersect(WT_genes, KO_genes)
columns <- genes

KO_sig_dpt_heatmap <- data.frame(matrix(nrow = 80, ncol = length(columns)))
WT_sig_dpt_heatmap <- data.frame(matrix(nrow = 80, ncol = length(columns)))

colnames(WT_sig_dpt_heatmap) <- columns
colnames(KO_sig_dpt_heatmap) <- columns

KO_sig_pval <- data.frame(matrix(ncol = 1, nrow = length(columns)))
WT_sig_pval <- data.frame(matrix(ncol = 1, nrow = length(columns)))

rownames(KO_sig_pval) <- columns
rownames(WT_sig_pval) <- columns

for (g in genes) {

  WT_plot_df <- WT_df %>% dplyr::select(gene = g, dpt)
  KO_plot_df <- KO_df %>% dplyr::select(gene = g, dpt)
  
  WT_plot <- ggplot(WT_plot_df, aes(dpt, gene)) +
                geom_smooth(se = F, method = "gam") +
                ggtitle(g) +
                theme_few() +
                theme(axis.title.x=element_blank(), axis.title.y=element_blank(), 
                  axis.text.x=element_blank(), axis.ticks.x = element_blank())
  
  KO_plot <- ggplot(KO_plot_df, aes(dpt, gene)) +
                  geom_smooth(se = F, method = "gam") +
                  ggtitle(g) +
                  theme_few() +
                  theme(axis.title.x=element_blank(), axis.title.y=element_blank(), 
                    axis.text.x=element_blank(), axis.ticks.x = element_blank())
  
  WT_data <- ggplot_build(WT_plot)$data[[1]]
  KO_data <- ggplot_build(KO_plot)$data[[1]]
  
  WT_sig_dpt_heatmap[,g] <- WT_data$y
  KO_sig_dpt_heatmap[,g] <- KO_data$y
  
  WT_tmp <- gam(gene ~ s(dpt), data=WT_plot_df)
  WT_p_val <- summary(WT_tmp)[4][[1]][1,5]
  
  KO_tmp <- gam(gene ~ s(dpt), data=KO_plot_df)
  KO_p_val <- summary(KO_tmp)[4][[1]][1,5]
  
  WT_sig_pval[g,1] <- WT_p_val
  KO_sig_pval[g,1] <- KO_p_val
  
}

# Filter based off of p-value
colnames(WT_sig_pval) <- c("p_val")
colnames(KO_sig_pval) <- c("p_val")

WT_sig_pval$p_val <- p.adjust(WT_sig_pval$p_val, method="bonferroni", 
                                n=length(WT_sig_pval$p_val))
KO_sig_pval$p_val <- p.adjust(KO_sig_pval$p_val, method="bonferroni", 
                                   n=length(KO_sig_pval$p_val))

WT_sig_genes <- WT_sig_pval[WT_sig_pval$p_val < 0.05, , drop=FALSE]
KO_sig_genes <- KO_sig_pval[KO_sig_pval$p_val < 0.05, , drop=FALSE]

WT_sig_genes <- na.omit(WT_sig_genes)
KO_sig_genes <- na.omit(KO_sig_genes)

WT_sig_genes$gene <- row.names(WT_sig_genes)
KO_sig_genes$gene <- row.names(KO_sig_genes)

WT_sig_genes <- WT_sig_genes%>%rename('WT p val'=p_val)
KO_sig_genes <- KO_sig_genes%>%rename('KO p val'=p_val)


WT_sig_genes%>%write_csv("WTsigzonatedgenes.csv")
KO_sig_genes%>%write_csv("KOsigzonatedgenes.csv")

length(setdiff(KO_sig_genes$gene,WT_sig_genes$gene))

zg <- merge(WT_sig_genes,KO_sig_genes,by='gene',all=T)
zg%>%write_csv("sigzonatedgenes_012_correctdpt.csv")
```

```{r F2E}
length(zg$KO.p.val)
length(zg$WT.p.val)-sum(is.na(zg$WT.p.val))
length(zg$KO.p.val)-sum(is.na(zg$KO.p.val))
zg2 <- na.omit(zg)
length(zg2$KO.p.val)
zgKO <- na.omit(zg[,c(1,3)])
zgWT <- na.omit(zg[,c(1,2)])
length(setdiff(zgKO$gene,zgWT$gene))
length(setdiff(zgWT$gene,zgKO$gene))
length(intersect(zgWT$gene,zgKO$gene))
length(zg2$WT.p.val)-sum(is.na(zg2$WT.p.val))
length(zg$KO.p.val)-sum(is.na(zg2$KO.p.val))
spl <- SplitObject(hepatocyte_obj_reint,split.by="perturbation")
length(row.names(spl$KO))
sum(!is.na(zg$WT.p.val))/sum(rowSums(spl$WT@assays$RNA@data)>0)
sum(!is.na(zg$KO.p.val))/sum(rowSums(spl$KO@assays$RNA@data)>0)
sum(!is.na(zg$gene))/sum(rowSums(hepatocyte_obj_reint@assays$RNA@data)>0)
```

```{r F2F}
dpt_vals <- hepatocyte_obj_reint$dpt
hepatocyte_obj_reint$dpt <- ((dpt_vals-min(dpt_vals))/(max(dpt_vals)-min(dpt_vals)))#-+1
hepatocyte_obj_reint$dpt <- hepatocyte_obj_reint$dpt*8
hepatocyte_obj_reint$binneddptgeno <- as.factor(paste0(hepatocyte_obj_reint$perturbation,"_",ceiling(hepatocyte_obj_reint$dpt)))
table(hepatocyte_obj_reint$binneddptgeno)
hepatocyte_obj_reint@meta.data$binneddptgeno[which(hepatocyte_obj_reint@meta.data$binneddptgeno == "KO_0")] <- "KO_1" # moves the one cell in bin KO_1 to KO_2
table(hepatocyte_obj_reint$binneddptgeno)

zg <- read.csv("sigzonatedgenes_012_correctdpt.csv")
zonatedgenes <- intersect(zg$gene,row.names(hepatocyte_obj_reint@assays$RNA@data))
meta <- hepatocyte_obj_reint@meta.data
exp_df <- hepatocyte_obj_reint@assays$RNA@data[zonatedgenes,] %>% t() %>% as.data.frame() # %>% as.matrix() #
df <- merge(meta, exp_df, by = 0)
vgroupg <- aggregate(df, list(df$binneddptgeno), FUN=mean)
heatmap <- as.data.frame(t(vgroupg[,c(1,30:length(colnames(vgroupg)))]))
names(heatmap) <- lapply(heatmap[1, ], as.character)
heatmap <- heatmap[-1,]
heatmap <- heatmap[,c(9:16,1:8)]

names <- lapply(
  rownames(heatmap), function(x) 
  bquote(italic(.(x ))))

column_names <- matrix(nrow = 18, ncol = 1)
column_names[1,] <- "Central"
column_names[5,] <- "Mid"
column_names[9,] <- "Portal"
column_names[10,] <- "Central"
column_names[14,] <- "Mid"
column_names[18,] <- "Portal"

for (i in 1:length(column_names)) {
  if (is.na(column_names[i,])) {
    column_names[i,] <- ""
  }
}

column_names <- lapply(
  column_names,
  function(x) bquote(bold(.(x ))))#capitalize

heatmapm <- sapply(heatmap, as.numeric)
if (min(heatmapm) < 0) {
  heatmapm <- heatmapm + (-min(heatmapm))  
}

colnames(heatmap) <- c("WT_1","WT_2","WT_3","WT_4","WT_5","WT_6","WT_7","WT_8","KO_1","KO_2","KO_3","KO_4","KO_5","KO_6","KO_7","KO_8")
colnames(heatmapm) <- c("WT_1","WT_2","WT_3","WT_4","WT_5","WT_6","WT_7","WT_8","KO_1","KO_2","KO_3","KO_4","KO_5","KO_6","KO_7","KO_8")

phm <- pheatmap(heatmapm,
         color = colorRampPalette(c('#408697','#F6F6F6','#8F0009'))(255),
         scale = 'row',
         fontsize = 16,
         fontsize_row = 10,
         fontsize_col = 10,
         angle_col = "0",
         cluster_rows = T,
         cluster_cols = F,
         border_color = NA,
         cutree_rows = 4,
         labels_col = " ",
         treeheight_row=100,
         annotation_names_row = F,
         main = "WT                              KO",
         filename = "zonated_binned_dpt_evenbins_correctgenes_heatmap_012_4.png",
         width = 15, height = 12,legend=T)


heatmap$cluster <- cutree(phm$tree_row, k = 4)
heatmap$gene <- row.names(heatmap)
heatmap <- heatmap[,c(17,18,1:16)]


zg$WT <- !is.na(zg$WT.p.val)
zg$KO <- !is.na(zg$KO.p.val)
zg$sig <- ""
zg[zg$WT,6] <- "CON ONLY"
zg[zg$KO,6] <- "L-KO ONLY"
zg[zg$WT&zg$KO,6] <- "BOTH"
combined <- merge(heatmap,zg[,c(1,6)])
combined <- combined[,c(1,2,19,3:18)]
combined2 <- combined
table(combined$cluster)
combined2[combined2$cluster==3,2] <- "A"
combined2[combined2$cluster==2,2] <- "B"
combined2[combined2$cluster==1,2] <- "C"
combined2[combined2$cluster==4,2] <- "D"
table(combined$cluster)

combined2%>%write_csv("clusteredsigzonatedgenes_evenbins_correctgenes.csv")
```

```{r bcatColnotlists}
str1 <- "Adh4
Aldh3a2
Aox1
Amacr
Aqp9
Ahr
Abcb4
Abcc12
Abcc2
Abcc4
Ces1g
Cyp1a1
Cyp1a2
Cyp2a5
Cyp2d40
Cyp2e1
Cyp27a1
Fmo1
Fmo2
Gsta3
Gsta4
Gstm3
Gstm6
Nfe2l2
Nr1i3
Por
Pon1
Gstm2
Cyb5b
Gsr
Gstm1
Slc10a2
Slc22a1
Xdh
Npc1
Stard4
Tmem97
Bdh1
Oxct1
Abhd4
Aldh1a1
Dgkd
Elovl7
Fabp12
Lipg
Mogat2
Osbpl8
Plbd1
Plekha8
Gpcpd1
Rdh9
Slc37a2
Sort1
Usp2
Vldlr
Crls1
Cept1
Napepld
Pgs1
Ptdss1
Pla2g6
Pla2g12a
Cerk
Col4a3bp
Asah1
Serinc5
Sptlc2
Sgms1
Sphk2
S1pr1
Azin1
Bckdhb
Car2
Glul
Oat
Rhbg
Slc7a5
Slc1a2
Slc1a4
Slc1a5
Slc16a10
Slc25a22
Nt5c2
Adcy6
Adss
Entpd5
Fignl1
Gda
Npr2
Pde2a
Pde4b
Pde4d
Slc28a1
Pfkfb2
Atp6v1b2
Cs
Dlat
Idh2
Idh3a
L2hgdh
Ldhb
Ldhd
Pdk4
Lhpp
Slc13a3
Slc25a13
Aspscr1
Pygb
Glb1
Gba2
Gys2
Myorg
Sord
Cbr3
Hsdl2
Nhlrc2
Prdx1
Prdx3
Selenoh
Srxn1
Alad
Blvrb
Cpox
Galk2
Gne
Slc35a3
Slc35b4
Gulo
Pdxk
Slc19a2
Phospho2
Dse
Manba
Pign
Galnt10
Galntl4
Hpgd
Tbxas1
Papss2
Cln6
Clcn5
Mfsd7c
Mmgt2
P2ry6
Scn4b
Slc16a12
Slc16a7
Slc22a23
Slc25a21
Slc30a1
Slc4a4
Slc41a3
Snx2
Snx5
Trpv2
Vat1
Haus8
Afp
Anapc4
Anln
Aspm
Aurka
Aurkb
Brca1
Cd2ap
Cdc42se1
Caprin1
Cdc20
Cdc27
Cdc42
Cdca2
Cdca3
Cetn3
Cenpf
Cenpl
Cenpn
Cenpt
Cep192
Ccnd1
Cdkn1c
Cdkn3
Dbf4
Dis3l2
Dcbld2
Dclre1a
Prim1
Espl1
Gtse1
Gsg2
Kif11
Kif20b
Kifap3
Lmln
Mcm4
Mcm6
Nek2
Ncapd2
Ncapg
Ncaph
Nusap1
Nubp1
Plk1
Plk2
Polk
Ska2l
Esco1
Ccnb1
Pkmyt1
Prc1
Rec8
Rpa1
Hjurp
Rbms1
Sik1
Spag5
Topbp1
Tacc3
Troap
Ube2c
Wee1
Csf1
Pdgfc
Tgfa
Aifm1
Aifm2
Atad5
Bax
Bcl2l1
Bcl2l11
Bcl2l14
Casp8
Dap
Dapk2
Endod1
Niacr1
Phlda1
Serinc3
Mcl1
Shf
Tnfaip8l1
Ptpn6
Ptprd
Ptprg
Hipk2
Abi2
Mertk
Dusp6
Dyrk3
Lrrk1
Mapkapk2
Mapk7
Map2k6
Map3k13
Map3k5
Map4k4
Mlkl
Mdfic
Mylk
Mtmr6
Ntrk2
Nuak2
Pim1
Taok3
Trpm7
Wnk4
Tlr12
Tifa
Trim8
Tnfaip3
Relb
Rel
Amigo2
Amica1
Cblb
Cxcl10
Cxcl2
Cx3cl1
Golm1
Hcls1
H2-Q1
Irf1
Irf8
Il1rl2
Il1r1
Il15
Il22ra1
Jam2
Lect2
Pik3ap1
Pag1
Patz1
Hsp90aa1
Sh3bp2
Pias3
Cxcl11
Sla
Socs3
Tapbp
Tox
Traf4
Traf3ip2
Tnfrsf19
Zc3hav1
Axin2
Bcl9l
Cacybp
Csnk1e
Daam1
Dixdc1
Fosl1
Fzd7
Lgr5
Lef1
Nkd1
Nlk
Notum
Ppap2b
Tspan12
Tcf7
Tsku
Arf6
Arl13b
Acap2
Agfg2
Bcar3
Dennd5a
Dennd5b
Dab2ip
Ect2
Igtp
Iqgap2
Mras
Net1
Rasip1
Rasal2
Rasgrf2
Rasl11b
Rasd1
Rnd3
Arhgap17
Arhgap18
Arhgef19
Asap1
Srgap3
Tbc1d1
Adrb2
Agtr1a
Arrb2
Atp2b2
Bmp7
Cib2
Depdc1b
Dnajc9
Egln3
Fgfrl1
Gpr116
Gpr98
Gnai2
Gng12
Homer2
Hcrtr2
Ihh
Inhbe
Inhbc
Irs1
Igf2r
Il17rd
Mrvi1
Nrg1
Pik3r1
Plcb1
Dnaja1
Calm1
Prkch
Ptplad1
Rab11fip2
Rab4a
Rin3
Max
Sorbs3
Spred1
Them4
Wwc1
Gpr182
Atad2
Zfp322a
Wwtr1
Rere
Dnmt1
H2afz
Hdac2
Phf15
Pbrm1
Rbl1
Nap1l1
Usp22
Uhrf1
Whsc1
Ezh2
Nrip1
Suz12
Zfp13
Atf3
Arid1b
Bhlhe40
Bclaf1
Cbx4
Cbx5
Ets2
Elf3
Fosb
Gata3
Grhl1
Hlf
Smad1
Smad5
Mybl1
Nkx1-2
Nr1d2
Olig1
Per1
Per2
Rara
Pbx3
Tbx3
Tef
Sp5
Tcf12
Tcf4
Zkscan3
Tcea3
Ccdc101
Csda
Lhx6
Phf20
Pold3
Ptrf
Prdm4
Hmgn1
Rqcd1
Rnf14
Mafg
Gtf2a2
Maff
Ang
Rnase4
Cpeb1
Ddx39
Exosc9
Hnrnpd
Rbm17
Pus10
Rbm22
Rbm9
Rod1
Nup93
Aars
Denr
Eif2ak4
Eif2b4
Gars
Impact
Lgtn
Samd4
Arpc1b
Jub
Actr2
Bcam
Nat8
Cml5
Cd164
Cgnl1
Cotl1
Cfl1
Col12a1
Dchs1
Dstn
Eln
Efna4
Epb4.1l1
Fmnl1
Gas7
Hmmr
Igsf11
Itgav
Icam1
Kif1b
Kif5b
Limk1
Mmp24
Mcam
Magi3
Mpzl1
Myo1g
Myo9b
Myo5b
Myo7b
Palmd
Arpc5
Myl12b
Tpm3
Plod1
Robo1
Sema3b
Sema3f
Dynll1
Stab2
Myo1c
Spnb1
Stard9
Tpx2
Tbcel
Tppp
Ttll11
Tubb5
Wisp2
Fem1b
Usp12
Usp14
Usp18
Usp20
Usp46
Ube2e2
Adamts17
Rnpep
Cast
Cpm
Dpp4
Enc1
Fbxo45
Habp2
Rnf43
Dcun1d1
Anxa7
Csrp2
Cys1
Ehd4
Rtl1
Epb4.1l5
Exoc6
Fkbp1a
Fut8
Gmfb
Grpel2
Hspb6
Lmna
Nphp1
Nek8
Narf
Pex13
Pitpnm2
Pros1
Pcp4l1
Tpr
Stx1b
Sntb1
Trak2
Tgm1
Ywhaz
Unc13b
Zcchc11
Zcchc6
Abhd12
Ankrd56
Armc8
Btnl9
Arpp19
Gstp3
Hrob
Coq10a
Ccdc157
Dhx32
D10Wsu52e
Airn
Knstrn
D6Wsu116e
Dym
Efr3b
Etl4
C630043F03Rik
Lrrc75aos2
Gm16984
D630024D03Rik
1110028F11Rik
2500002B13Rik
Tbx3os1
Gm13872
4732463B04Rik
Gm13571
A930001C03Rik
3010003L21Rik
Etohd2
Rian
Emp2
Epb4.1l4b
Rimoc1
Fbxw9
Fam102a
Fam107b
Fam110b
Fam20c
Fam82a1
Fhad1
Fktn
Greb1
Gcap14
Hdhd3
Hn1
2310028H24Rik
Fam89a
Iffo2
Klhl8
Leprotl1
Lrrc45
Ly6c1
Msmp
Mmrn2
Myom3
Nbeal1
Nav2
Nptx1
Pdzrn3
Pde4dip
Plac8
Pdgfrl
Plekha7
Phldb2
Gm129
Gm5158
Ptplb
Paqr4
Prr11
Prom1
Pdilt
Reep1
Rell1
1190005I06Rik
1300014I06Rik
Chp1
2010002N04Rik
2200001I15Rik
2310030N02Rik
Mkrn2os
Rmdn2
4930420K17Rik
4931406C07Rik
4933429F08Rik
5830403L16Rik
6430548M08Rik
Mir670hg
Rnf38
Rufy2
Sec14l1
Secisbp2l
Sdccag1
Efhd2
Znrf3
Qk
Prr18
Spats2
Tex2
Tex264
Ttc14
Ttc38
Thumpd1
Tmem106a
Tmem184b
Tmem50b
Dram2
Tmem86a
Trim47
Zfp334
Zfp768
Zfp81"

str2 <- "F11
F7
Fga
Fgb
Fgg
Cpb2
Ggcx
Kng1
Arg1
Asl
Ass1
Cps1
Otc
Afmid
Amdhd1
Aspg
Ccbl1
Ftcd
Gls2
Haao
Hal
Inmt
Kynu
Mccc2
Sardh
Tdo2
Uroc1
Agxt2l1
Got1
Aqp8
Cbs
Cth
Gldc
Gm4952
Prodh2
Qdpr
Slc22a7
Slc3a1
Car14
Car3
Acacb
Acly
Acsl1
Acss2
Angptl3
Angptl4
Aqp4
Elovl2
Elovl5
Fetub
Lpin1
Pecr
Scap
Scd1
Slc27a5
Slc37a1
Tff3
Bdh2
Hsd17b13
Lmf1
Alb
Apoa4
Apoa5
Apoc2
Apoc3
Apon
Slc10a1
Ces1e
Ces2a
Ces3a
Ces4a
Cyp17a1
Cyp3a25
Cyp46a1
Cyp7b1
Cyp8b1
Dhrs9
Hsd11b1
Hsd17b2
Hsd17b6
Retsat
Sdr42e1
Ugt3a1
Osbp2
Agpat2
Chka
Dak
Gm2a
Ptgds
Slco2a1
Agxt
Fbp1
G6pc
Grhpr
Pck1
Sds
Sdsl
Slc37a4
Cisd1
Cyb561
Slc25a47
Ak3l1
Aldob
Khk
Ppp1r3c
Abca8a
Abcc3
Aldh1b1
Cyp2b10
Cyp2b23
Cyp2f2
Cyp2j5
Cyp4a12a
Mosc1
Slc16a6
Sult5a1
Prxl2a
Aldh1l1
Rdh16f2
Ggt7
H6pd
Pyroxd2
Slc25a32
Cat
Gdf15
Hao1
5033411D12Rik
Ethe1
Hebp1
Pde4c
Tymp
Uox
Hamp2
Pzp
Serpina1a
Serpina1b
Serpina1c
Serpina1d
Serpina1e
Serpina3k
Serpina3n
Serpina4-ps1
Serpina9
Serpina11
Serpina12
Serpinf1
Serpinf2
Serpinb1a
Col15a1
Col27a1
Col5a3
Gpc1
Itih3
Man2a2
Pcsk6
Sdc4
Sspo
St3gal5
St6gal1
Lad1
Cdh1
Cldn1
Fam129b
Igfals
Lama3
Arhgap10
Arhgap24
Plxna2
Rarres1
Shroom1
Svil
Xirp1
Celsr1
Efna3
Loxl4
Bmp4
Bmper
Grem2
Ltbp2
Nedd4l
Smad9
Ddit4
Egfr
Evc
Fgfr2
Gpr12
Hgfac
Mmd2
Plch2
Rgs7
St5
Ulk1
Arntl
Bhlha15
Mbd1
Mycl1
Nfil3
Npas2
Gnmt
1100001G20Rik
AI182371
C4a
C8a
C8b
Cfb
Cfh
Ceacam1
Fam46c
Nlrp12
Pigr
Prtn3
Raet1a
Rnf125
Apcs
Bcl6
Chac1
Dapk1
Gas2
Htra4
Igfbp1
Mt1
Mt2
Cables1
Cdkn1a
Inca1
Igf1
Igfbp2
5430407P10Rik
Acpp
Adck5
Dclk3
Adam11
Asb2
Josd2
Prepl
Wsb1
Agt
B3galt1
Chrna4
Creld2
Derl3
Enpp2
Herpud1
Keg1
Mcart1
Plbd2
Scnn1a
Sfxn1
Slc15a5
Slc30a10
Slc41a2
Slc6a12
Syne1
Syvn1
Tars
Tmem205
Tmie
Tpst1
Tspan33
1810046K07Rik
Hectd2os"
```

```{r F2G}
pw <- c(c(str_split(str1,'\n')),c(str_split(str2,'\n')))
names(pw)[[length(pw)-1]] <- "colup"
names(pw)[[length(pw)]] <- "coldown"
#https://ftp.ncbi.nlm.nih.gov/gene/DATA/GENE_INFO/Mammalia/
Mm <- read.delim("Mus_musculus.gene_info.gz",sep="\t")
Cols <- c("Synonyms","Symbol")
x <- alias2SymbolUsingNCBI(unlist(pw), Mm, required.columns=Cols)
x$pwgene <- unlist(pw)

syn <- strsplit(x$Synonyms,split="[|]")
names(syn) <- x$Symbol
for (i in seq(length(x$Symbol))){
  if(syn[[i]][1]=="-"){
    syn[[i]] <- x$Symbol[i]
  }
  else{
    syn[[i]] <- append(x$Symbol[i],syn[[i]])
  }
}

x$hepname <- x$pwgene
x[!(x$pwgene%in%row.names(hepatocyte_obj_reint)),"hepname"] <- NA

# sum(is.na(x$hepname))
for (i in x[is.na(x$hepname),"Symbol"]){
  #print(paste("outer",i))
  for (j in seq(length(syn[i][[1]]))){
    #print(paste("inner",j))
    if (syn[i][[1]][j]%in%row.names(hepatocyte_obj_reint)){
      x[x$Symbol==i,"hepname"] <- syn[i][[1]][j]
      break
    }
  }
}
# sum(is.na(x$hepname))
x[is.na(x$hepname),"hepname"] <- x[is.na(x$hepname),"pwgene"]#all 11 genes not in hep obj use initial name
x$pathway <- ""
x[x$pwgene%in%pw[[1]],"pathway"] <- "up"
x[x$pwgene%in%pw[[2]],"pathway"] <- "down"
z <- pivot_wider(x[,c(4,5)],names_from = pathway,values_from = hepname)
#z$up
pathways <- c(z$up,z$down)
names(pathways) <- c("up","down")
zg <- read_csv("clusteredsigzonatedgenes_evenbins_correctgenes.csv")
cA <- zg[zg$cluster=='A',]$gene
cB <- zg[zg$cluster=='B',]$gene
cC <- zg[zg$cluster=='C',]$gene
cD <- zg[zg$cluster=='D',]$gene
zglist <- list(cA,cB,cC,cD)
names(zglist) <- c("A","B","C","D")

univ <- union(row.names(hepatocyte_obj_reint),unique(unlist(pathways)))
#setdiff(unique(unlist(pathways)),row.names(hepatocyte_obj_reint))
pathways$up[duplicated(pathways$up)]
fgsea_oracolnot <- lapply(seq_along(zglist), function(i) {
  fora(pathways = pathways,
       genes = zglist[[i]], # genes in cluster i
       universe = univ, # all genes in object or pathways = 21616
       minSize = 1, 
       maxSize = 2001) %>% 
    mutate(cluster = names(zglist)[i]) # add cluster column
}) %>% 
  data.table::rbindlist() %>% # combine tables
  #filter(padj < 0.05) %>%
  arrange(cluster, padj)


# create dot plots
fgsea_oracolnot$`Overlap %`<-100*fgsea_oracolnot$overlap/fgsea_oracolnot$size
fgsea_oracolnot$pathway <- factor(fgsea_oracolnot$pathway, levels = c("up", "down"))
fgsea_oracolnot$cluster <- factor(fgsea_oracolnot$cluster, levels = c("A", "B", "C", "D"))
fgsea_oracolnot$csize <- NA
fgsea_oracolnot[fgsea_oracolnot$cluster=="A","csize"] <- length(zglist[[1]])
fgsea_oracolnot[fgsea_oracolnot$cluster=="B","csize"] <- length(zglist[[2]])
fgsea_oracolnot[fgsea_oracolnot$cluster=="C","csize"] <- length(zglist[[3]])
fgsea_oracolnot[fgsea_oracolnot$cluster=="D","csize"] <- length(zglist[[4]])
fgsea_oracolnot$`Cluster Overlap %` <- 100*fgsea_oracolnot$overlap/fgsea_oracolnot$csize

ggplot(fgsea_oracolnot,aes(x=cluster,y=pathway))+geom_point(aes(size=`Cluster Overlap %`,color=-log10(padj)))+theme_classic()+labs(title=element_blank(),y=element_blank(),x=element_blank())+theme(axis.text = element_blank(),axis.line = element_line(colour = 'black', size = 0.7),axis.ticks = element_line(colour = 'black', size = 0.7),axis.ticks.length = unit(0,"cm"))#+theme(panel.grid = element_line(color = "gray",size = 0.75,linetype = 2),panel.background = element_rect(fill = "white"))
ggsave("colnotdotplotclusteroverlap.png",width=3,height=3)
```


```{r ST2}
df <- read.csv("clusteredsigzonatedgenes_evenbins_correctgenes.csv")
df <- df[,c(1:3)]
df2 <- data.frame(str_split(str1,'\n'))
names(df2) <- "gene"
df2$list <- "Colnot_InducedbyBcat"
df3 <- data.frame(str_split(str2,'\n'))
names(df3) <- "gene"
df3$list <- "Colnot_InhibitedbyBcat"
df4 <- merge(df2,df3,all=T)
df5 <- merge(df,df4,all.x=T)
df5[is.na(df5$list),]$list <- "None"
df5%>%write.csv("Clustered_sigzonatedgenes_bcat.csv",row.names = F)
df <- read.csv("Clustered_sigzonatedgenes_bcat.csv")
hepatocyte_obj_reint <- readRDS("hepatocyte_obj_012_reint_mtcountfeat032724.rds")
dpt_vals <- hepatocyte_obj_reint$dpt
hepatocyte_obj_reint$dpt <- ((dpt_vals-min(dpt_vals))/(max(dpt_vals)-min(dpt_vals)))#-+1
hepatocyte_obj_reint$dpt <- hepatocyte_obj_reint$dpt*8
hepatocyte_obj_reint$binneddptgeno <- as.factor(paste0(hepatocyte_obj_reint$perturbation,"_",ceiling(hepatocyte_obj_reint$dpt)))
table(hepatocyte_obj_reint$binneddptgeno)
hepatocyte_obj_reint@meta.data$binneddptgeno[which(hepatocyte_obj_reint@meta.data$binneddptgeno == "KO_0")] <- "KO_1" # moves the one cell in bin KO_1 to KO_2
table(hepatocyte_obj_reint$binneddptgeno)
df2 <- data.frame(AverageExpression(hepatocyte_obj_reint,assays="RNA",slot='data',group.by = "binneddptgeno"))
names(df2) <- c("KO_1","KO_2","KO_3","KO_4","KO_5","KO_6","KO_7","KO_8","WT_1","WT_2","WT_3","WT_4","WT_5","WT_6","WT_7","WT_8")
df2$Gene <- row.names(df2)
dft <- merge(df,df2)
dft <- dft[,c(1,2,13:20,5:12,3,4)]
dft%>%write.csv("ST2.csv")
```

## Glutamine/Glutamate Heatmap

```{r F3B}
reactome <- read.csv("ReactomePathways.csv")
reactomet <- reactome %>% t() %>% as.data.frame()
reactomet$V2656 <- rownames(reactomet)
rownames(reactomet) <- NULL
names(reactomet) <- reactomet[2,]
reactomet <- reactomet[-2,]
Mlistold <- c("Glul","Gls2","Nags","Cps1","Otc","Ass1","Asl","Arg1","Arg2")
Mlistnew <- c("Slc1a2", "Glul", "Oat", "Gls2", "Cps1", "Otc", "Ass1", "Arg1", "Asl","Slc38a2", "Rhbg","Slc1a5", "Slc38a1","Slc38a2")
ggenes <- union(str_to_title(as.data.frame(as.data.frame(as.data.frame(reactomet$`R-HSA-8964539`)[as.data.frame(reactomet$`R-HSA-8964539`)[1]!=""])[-1,])[,1]),Mlistold)
ggenes <- union(ggenes,Mlistnew)
ggenes <- intersect(ggenes,row.names(hepatocyte_obj_reint@assays$RNA@data))
ggenes <- ggenes[!(ggenes %in% c("Glud1","Aco2","Idh2","Ogdh","Pycrl","Kyat1","Got2"))]#Not in pathway of interest
x <- data.frame(t(hepatocyte_obj_reint@assays$RNA@data[ggenes,]))
x$bdpt <- as.factor(hepatocyte_obj_reint$binneddptgeno)
for (i in colnames(x[,1:20])){
  if (i==colnames(x)[1]){
    celldf <- aggregate(as.formula(paste0(i,"~bdpt")),x, function(x) sum(x >= 0, na.rm = TRUE))
    colnames(celldf)[2] <- "totalcells"
  }
  celldf <- merge(celldf,aggregate(as.formula(paste0(i,"~bdpt")),x, function(x) sum(x > 0, na.rm = TRUE)))
}
celldf2 <- celldf/celldf[,2]
celldf2 <- celldf2[,-c(1,2)]
celldf3 <- celldf2[, colSums(celldf2 > 0.1) >= 1]#at least 10% of cells with UMI count>0 in at least one bin


meta <- hepatocyte_obj_reint@meta.data
ggenes <- intersect(ggenes,colnames(celldf3))
exp_df <- hepatocyte_obj_reint@assays$RNA@data[ggenes,] %>% t() %>% as.data.frame() # %>% as.matrix() #
df <- merge(meta, exp_df, by = 0)
vgroupg <- aggregate(df, list(df$binneddptgeno), FUN=mean)
heatmap <- as.data.frame(t(vgroupg[,c(1,30:length(colnames(vgroupg)))]))
names(heatmap) <- lapply(heatmap[1, ], as.character)
heatmap <- heatmap[-1,]
heatmap <- heatmap[,c(9:16,1:8)]

names <- lapply(
  rownames(heatmap), function(x) 
  bquote(italic(.(x ))))

column_names <- matrix(nrow = 18, ncol = 1)
column_names[1,] <- "Central"
column_names[5,] <- "Mid"
column_names[9,] <- "Portal"
column_names[10,] <- "Central"
column_names[14,] <- "Mid"
column_names[18,] <- "Portal"

for (i in 1:length(column_names)) {
  if (is.na(column_names[i,])) {
    column_names[i,] <- ""
  }
}

column_names <- lapply(
  column_names,
  function(x) bquote(bold(.(x ))))

heatmap <- sapply(heatmap, as.numeric)
if (min(heatmap) < 0) {
  heatmap <- heatmap + (-min(heatmap))  
}
pheatmap(heatmap,
         color = colorRampPalette(c('#408697','#F6F6F6','#8F0009'))(255),
         scale = 'row',
         fontsize = 16,
         fontsize_row = 10,
         fontsize_col = 10,
         angle_col = "0",
         cluster_rows = T,
         cluster_cols = F,
         border_color = NA,
         labels_row = as.expression(ggenes),
         labels_col = "",
         annotation_names_row = F,
         treeheight_row = 50,
         main = "WT                              KO",
         filename = "filtered_10pctanybin_finallist_Gln_Heatmap.png",
         width = 7, height = 4,legend=T)
```

## DPT Traces

```{r S4B}
df <- hepatocyte_obj_reint@assays$RNA@data
colnm <- row.names(df)
df <- data.frame(t(df))
colnames(df) <- colnm
hepatocyte_obj_reint$bdpt10 <- as.factor(paste0(hepatocyte_obj_reint$perturbation,"_",ceiling(((hepatocyte_obj_reint$dpt-min(hepatocyte_obj_reint$dpt))/(max(hepatocyte_obj_reint$dpt)-min(hepatocyte_obj_reint$dpt)))*10)))
df$bdpt10 <- hepatocyte_obj_reint$bdpt10
df[df$bdpt10 =='KO_0',]$bdpt10 <- 'KO_1' # moves the one cell in bin KO_0 to KO_1
#levels(hepatocyte_obj_reint$bdpt10)

expr <- df %>% 
  group_by(bdpt10) %>% 
  summarise(mean = ExpMean(Pck1),
            std = ExpSD(Pck1),n=n())
expr$se <- expr$std/sqrt(expr$n)
expr$X <- as.numeric(substring(expr$bdpt10,4))-1
expr$geno <- substring(expr$bdpt10,1,2)
expr$pct <- 1
expr$sepct <- 1
expr[expr$geno=='WT',]$pct <- expr[expr$geno=='WT',]$mean/sum(expr[expr$geno=='WT',]$mean)
expr[expr$geno=='KO',]$pct <- expr[expr$geno=='KO',]$mean/sum(expr[expr$geno=='KO',]$mean)
expr[expr$geno=='WT',]$sepct <- expr[expr$geno=='WT',]$se*expr[expr$geno=='WT',]$pct/expr[expr$geno=='WT',]$mean
expr[expr$geno=='KO',]$sepct <- expr[expr$geno=='KO',]$se*expr[expr$geno=='KO',]$pct/expr[expr$geno=='KO',]$mean
expr[expr$geno=='WT',]$geno <- "CON"
expr[expr$geno=='KO',]$geno <- "L-KO"
write.csv(expr,"Pck1_10bin_DPT.csv")
ggplot(expr,aes(x=X,y=pct,group_by=geno,color))+ geom_ribbon(data=expr[expr$geno=='CON',],aes(x = X,ymin = pct-sepct, ymax = pct+sepct,fill = "CON"),alpha=0.5, inherit.aes = FALSE)+ geom_ribbon(data=expr[expr$geno=='L-KO',],aes(x = X,ymin = pct-sepct, ymax = pct+sepct,fill = "L-KO"),alpha=0.5, inherit.aes = FALSE)+scale_fill_manual(name="Genotype",breaks=c("CON","L-KO"),values = c("L-KO"="#52D6F4","CON"="#8F0009"))+geom_line(data=expr[expr$geno=='CON',],color="#8F0009")+geom_line(data=expr[expr$geno=='L-KO',],color="#52D6F4")+ggtitle("Pck1")


expr <- df %>% 
  group_by(bdpt10) %>% 
  summarise(mean = ExpMean(G6pc),
            std = ExpSD(G6pc),n=n())
expr$se <- expr$std/sqrt(expr$n)
expr$X <- as.numeric(substring(expr$bdpt10,4))-1
expr$geno <- substring(expr$bdpt10,1,2)
expr$pct <- 1
expr$sepct <- 1
expr[expr$geno=='WT',]$pct <- expr[expr$geno=='WT',]$mean/sum(expr[expr$geno=='WT',]$mean)
expr[expr$geno=='KO',]$pct <- expr[expr$geno=='KO',]$mean/sum(expr[expr$geno=='KO',]$mean)
expr[expr$geno=='WT',]$sepct <- expr[expr$geno=='WT',]$se*expr[expr$geno=='WT',]$pct/expr[expr$geno=='WT',]$mean
expr[expr$geno=='KO',]$sepct <- expr[expr$geno=='KO',]$se*expr[expr$geno=='KO',]$pct/expr[expr$geno=='KO',]$mean
expr[expr$geno=='WT',]$geno <- "CON"
expr[expr$geno=='KO',]$geno <- "L-KO"
write.csv(expr,"G6pc_10bin_DPT.csv")
ggplot(expr,aes(x=X,y=pct,group_by=geno,color))+ geom_ribbon(data=expr[expr$geno=='CON',],aes(x = X,ymin = pct-sepct, ymax = pct+sepct,fill = "CON"),alpha=0.5, inherit.aes = FALSE)+ geom_ribbon(data=expr[expr$geno=='L-KO',],aes(x = X,ymin = pct-sepct, ymax = pct+sepct,fill = "L-KO"),alpha=0.5, inherit.aes = FALSE)+scale_fill_manual(name="Genotype",breaks=c("CON","L-KO"),values = c("L-KO"="#52D6F4","CON"="#8F0009"))+geom_line(data=expr[expr$geno=='CON',],color="#8F0009")+geom_line(data=expr[expr$geno=='L-KO',],color="#52D6F4")+ggtitle("G6pc")
```


# Response to Reviewers

```{r ClustersnotAffected}
# Prove some zonation markers stay the same
seurat_integrated <- readRDS("TCF_Knockout_seurat-integrated-mtcountfeat_012.rds")
Idents(seurat_integrated) <- "sample"
spl <- SplitObject(seurat_integrated)
for(i in seq(length(spl))){
  # print(i)
  Idents(spl[[i]]) <- "seurat_clusters"
  df <- FindMarkers(spl[[i]],ident.1 = "0",ident.2 = "1")
  names(df) <- paste0(names(df),"_",unique(spl[[i]]$sample))
  df$gene <- row.names(df)
  # print(unique(Idents(spl[[i]])))
  if (i==1){
    tdf <- df
  }
  else{
    tdf <- merge(tdf,df,all=T)
  }
}
row.names(tdf) <- tdf$gene
tdf <- tdf[,c(3,8,13,18,23,28,33,38,43,48)]
tdf2 <- drop_na(tdf)
names(tdf2) <- str_split_fixed(names(tdf2),"_",5)[,5]
names(tdf2) <- c("KO 1","KO 2","KO 3","KO 4","KO 5","WT 1","WT 2","WT 3","WT 4","WT 5")
pheatmap(tdf2[,c(6:10,1:5)],
         color = colorRampPalette(c('#408697','#F6F6F6','#8F0009'))(255),
         scale = 'none',
         fontsize = 16,
         fontsize_row = 10,
         fontsize_col = 10,
         angle_col = "0",
         cluster_rows = T,
         cluster_cols = F,
         border_color = NA,
         # labels_col = " ",
         treeheight_row=100,
         annotation_names_row = F,
         annotation_names_col = T,
         # main = "WT                              KO",
         filename = "log2fc_PPvPC_bysample_geneswvaluesineachsample_heatmap.png",
         width = 15, height = 12,legend=T)
```

```{r DPT_for_all_gluts}
hepatocyte_obj_reint <- readRDS("hepatocyte_obj_012_reint_mtcountfeat032724.rds")
# hepatocyte_obj_reint$dpt10 <- 10*((hepatocyte_obj_reint$dpt-min(hepatocyte_obj_reint$dpt))/(max(hepatocyte_obj_reint$dpt)-min(hepatocyte_obj_reint$dpt)))
# hepatocyte_obj_reint$bdpt10 <- ceiling(((hepatocyte_obj_reint$dpt-min(hepatocyte_obj_reint$dpt))/(max(hepatocyte_obj_reint$dpt)-min(hepatocyte_obj_reint$dpt)))*10)
# df[df$bdpt10 =='0',]$bdpt10 <- '1'
df <- hepatocyte_obj_reint@assays$RNA@data
colnm <- row.names(df)
df <- data.frame(t(df))
colnames(df) <- colnm
hepatocyte_obj_reint$bdpt10 <- as.factor(paste0(hepatocyte_obj_reint$perturbation,"_",ceiling(((hepatocyte_obj_reint$dpt-min(hepatocyte_obj_reint$dpt))/(max(hepatocyte_obj_reint$dpt)-min(hepatocyte_obj_reint$dpt)))*10)))
df$bdpt10 <- hepatocyte_obj_reint$bdpt10
df[df$bdpt10 =='KO_0',]$bdpt10 <- 'KO_1'
# hepatocyte_obj_reint$bdpt10 <- ceiling(((hepatocyte_obj_reint$dpt-min(hepatocyte_obj_reint$dpt))/(max(hepatocyte_obj_reint$dpt)-min(hepatocyte_obj_reint$dpt)))*10)
# df$bdpt10 <- hepatocyte_obj_reint$bdpt10
# df[df$bdpt10 =='0',]$bdpt10 <- '1'

for(i in findgenes(hepatocyte_obj_reint,"Slc2a")){
  # print(df$as.name(i)))
  expr <- df %>% 
    group_by(bdpt10) %>% 
    summarise(mean = ExpMean(eval(as.name(i))),
              std = ExpSD(eval(as.name(i))),n=n())
  expr$se <- expr$std/sqrt(expr$n)
  expr$X <- as.numeric(substring(expr$bdpt10,4))-1
  expr$geno <- substring(expr$bdpt10,1,2)
  expr$pct <- 1
  expr$sepct <- 1
  expr[expr$geno=='WT',]$pct <- expr[expr$geno=='WT',]$mean/sum(expr[expr$geno=='WT',]$mean)
  expr[expr$geno=='KO',]$pct <- expr[expr$geno=='KO',]$mean/sum(expr[expr$geno=='KO',]$mean)
  expr[expr$geno=='WT',]$sepct <- expr[expr$geno=='WT',]$se*expr[expr$geno=='WT',]$pct/expr[expr$geno=='WT',]$mean
  expr[expr$geno=='KO',]$sepct <- expr[expr$geno=='KO',]$se*expr[expr$geno=='KO',]$pct/expr[expr$geno=='KO',]$mean
  expr[expr$geno=='WT',]$geno <- "CON"
  expr[expr$geno=='KO',]$geno <- "L-KO"
  write.csv(expr,paste0(i,"_10bin_DPT.csv"))
}
```

